### ISSUE TITLE
Beginning.

### ISSUE THREAD

**Issue by f4004** [TheMaverickProgrammer/Swoosh#7]
Hello. I plan to work with this library soon. But I don't know much about it. I am using GUI for GUI. Would it be a problem? Can I adding effects to the button on TGUI with Swoosh?

**Comment by TheMaverickProgrammer** [comment]
You can use the shader objects (shader.h) and tween utilities (ease.h) to
make custom GUI effects. You'd have to do a little wiring since it doesnt
come out of the box supporting your library but thats all Swoosh does under
the hood anyway.

Swoosh does come out of the box ready to be used for screen 'state'
management for your SFML applications and transition effects are
immediately applied to them
